In [33]:
!pip install category-encoders

Collecting category-encoders
  Downloading category_encoders-2.6.4-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\romeo\anaconda3\lib\site-packages (from category-encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\romeo\anaconda3\lib\site-packages (from category-encoders) (1.4.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\romeo\anaconda3\lib\site-packages (from category-encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\romeo\anaconda3\lib\site-packages (from category-encoders) (0.14.2)
Requirement already satisfied: pandas>=1.0.5 in c:\users\romeo\anaconda3\lib\site-packages (from category-encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\romeo\anaconda3\lib\site-packages (from category-encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\romeo\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\romeo\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\romeo\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2023.3)
Requirement already satisfied: six in c:\users\romeo\anaconda3\lib\site-packages (from patsy>=0.5.1->category-encoders) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\romeo\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category-encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\romeo\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category-encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\romeo\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category-encoders) (23.2)
Downloading category_encoders-2.6.4-py2.py3-none-any.whl (82 kB)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.6.4

Import necessary libraries

In [35]:
# import libs

import warnings
warnings.filterwarnings("ignore")

import pandas as pd

import category_encoders as ce

In [7]:
pd.set_option("display.max_columns", None) #display max columns

In [9]:
df = pd.read_csv("5G_energy_consumption_dataset.csv", encoding="latin-1") #import data

In [43]:
df

           BS     Energy      load  ESMODE   TXpower  BS_encoded
0         B_0  64.275037  0.487936     0.0  7.101719   73.087415
1         B_0  55.904335  0.344468     0.0  7.101719   73.087415
2         B_0  57.698057  0.193766     0.0  7.101719   73.087415
3         B_0  55.156951  0.222383     0.0  7.101719   73.087415
4         B_0  56.053812  0.175436     0.0  7.101719   73.087415
...       ...        ...       ...     ...       ...         ...
92624  B_1018  14.648729  0.087538     0.0  7.325859   22.481489
92625  B_1018  14.648729  0.082635     0.0  7.325859   22.481489
92626  B_1018  13.452915  0.055538     0.0  7.325859   22.481489
92627  B_1018  13.602392  0.058077     0.0  7.325859   22.481489
92628  B_1018  13.303438  0.048173     0.0  7.325859   22.481489

[92629 rows x 6 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92629 entries, 0 to 92628
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Time     92629 non-null  object
 1   BS       92629 non-null  object
 2   Energy   92629 non-null  float64
 3   load     92629 non-null  float64
 4   ESMODE   92629 non-null  float64
 5   TXpower  92629 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.2+ MB

In [17]:
df = df.drop("Time", axis=1) #drop time

In [23]:
df.describe(include = "all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
BS,92629,923,B_583,130,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Energy,92629.0,NaN,NaN,NaN,28.138997,13.934645,0.747384,18.236173,24.06577,35.724963,100.0
load,92629.0,NaN,NaN,NaN,0.244705,0.234677,0.0,0.05737,0.16555,0.363766,0.993957
ESMODE,92629.0,NaN,NaN,NaN,0.081361,0.382317,0.0,0.0,0.0,0.0,4.0
TXpower,92629.0,NaN,NaN,NaN,6.765427,0.309929,5.381166,6.427504,6.875934,6.875934,8.375336

In [25]:
df["BS"].value_counts()`

BS
B_583     130
B_261     128
B_728     128
B_669     128
B_512     126
         ...
B_1018     16
B_921      14
B_905      13
B_854       1
B_835       1
Name: count, Length: 923, dtype: int64

In [39]:
# Target Encoding
encoder = ce.TargetEncoder(cols=['BS'])
df['BS_encoded'] = encoder.fit_transform(df['BS'], df['Energy'])

In [47]:
df

           BS     Energy      load  ESMODE   TXpower  BS_encoded
0         B_0  64.275037  0.487936     0.0  7.101719   73.087415
1         B_0  55.904335  0.344468     0.0  7.101719   73.087415
2         B_0  57.698057  0.193766     0.0  7.101719   73.087415
3         B_0  55.156951  0.222383     0.0  7.101719   73.087415
4         B_0  56.053812  0.175436     0.0  7.101719   73.087415
...       ...        ...       ...     ...       ...         ...
92624  B_1018  14.648729  0.087538     0.0  7.325859   22.481489
92625  B_1018  14.648729  0.082635     0.0  7.325859   22.481489
92626  B_1018  13.452915  0.055538     0.0  7.325859   22.481489
92627  B_1018  13.602392  0.058077     0.0  7.325859   22.481489
92628  B_1018  13.303438  0.048173     0.0  7.325859   22.481489

[92629 rows x 6 columns]

In [61]:
#Feature selection

X = df[['BS_encoded', 'TXpower', 'load', 'ESMODE']]
y = df['Energy']

In [63]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [65]:
# Separate the DataFrame into two: features and the target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [69]:
X_train

       BS_encoded   TXpower      load  ESMODE
42091   20.389699  6.875934  0.306240     0.0
27803   43.311928  7.100897  0.273149     0.0
40368   16.176093  6.427504  0.121560     0.0
9254    25.282776  6.427504  0.075800     0.0
76007   38.393443  6.726457  0.845980     0.0
...           ...       ...       ...     ...
6265    34.933214  6.875934  0.688500     0.0
54886   60.181719  7.101719  0.048620     0.0
76820   21.266416  6.875934  0.431660     0.0
860     30.335659  7.100897  0.042628     0.0
15795   23.774474  6.875934  0.166890     0.0

[74103 rows x 4 columns]

In [71]:
y_train

42091    13.751868
27803    44.394619
40368    15.994021
9254     25.859492
76007    42.002990
           ...
6265     41.405082
54886    51.420030
76820    26.158445
860      30.642750
15795    21.524664
Name: Energy, Length: 74103, dtype: float64

Machine learning alogrithms

In [73]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the model
linear_reg = LinearRegression()

# Fit the model to the training data
linear_reg.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred_linear = linear_reg.predict(X_test_scaled)

# Evaluate the model
rmse_linear = np.sqrt(mean_squared_error(y_test, y_pred_linear))
r2_linear = r2_score(y_test, y_pred_linear)

print(f"Linear Regression:\n RMSE: {rmse_linear:.4f}\n RÂ²: {r2_linear:.4f}\n")

Linear Regression:
 RMSE: 4.1687
 RÂ²: 0.9084

In [75]:
from sklearn.ensemble import GradientBoostingRegressor

# Initialize the model
gb_reg = GradientBoostingRegressor()

# Fit the model to the training data
gb_reg.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred_gb = gb_reg.predict(X_test_scaled)

# Evaluate the model
rmse_gb = np.sqrt(mean_squared_error(y_test, y_pred_gb))
r2_gb = r2_score(y_test, y_pred_gb)

print(f"Gradient Boosting Regressor:\n RMSE: {rmse_gb:.4f}\n RÂ²: {r2_gb:.4f}\n")

Gradient Boosting Regressor:
 RMSE: 3.5302
 RÂ²: 0.9343

In [77]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Initialize the model
xgb_reg = xgb.XGBRegressor()

# Fit the model to the training data
xgb_reg.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred_xgb = xgb_reg.predict(X_test_scaled)

# Evaluate the model
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2_xgb = r2_score(y_test, y_pred_xgb)

print(f"XGBoost Regressor:\n RMSE: {rmse_xgb:.4f}\n RÂ²: {r2_xgb:.4f}\n")

XGBoost Regressor:
 RMSE: 3.1086
 RÂ²: 0.9491